# Conclusion
In conclusion, we hope that the project has provided an deep and thorough exploration of bird distributions, species diversity, and sighting patterns (location and time) in Manhattan. Location wise, we found that Central Park serves as the prime hotspot for birdwatching, with areas including the Great Lawn, Sheep Meadow, and North Woods having some of the highest bird diversity. Besides Central Park, Randall's Island Park and Inwood Hill Park are also great choices to catch a bird or two. Regarding bird species, House Sparrow, American Robin, and European Starling are some of the most spotting species, if you are especially interested in rare species like Great Horned Owl and Yellow-billed Cuckoo, then Central Park should be the optimal destination. Time period wise, spring and fall were identified as the best seasons for birdwatching, and getting up early to catch your favorite birds would also be such a great idea!
However, we also have to admit some limitations of our analysis. The project relies on a subset of all the eBird data, which might not capture every birding activity in Manhattan. Given an opportunity, we would like to apply the analysis methods to a larger and more comprehensive dataframe.
Talking about some future directions we can take, we think that it would be a great idea to do some dynamic trackings which integrate real-time data to track bird movements and seasonal trends. Since we were not able to factor in weather data this time, we would love to incorporate weather data to analyze its influence on bird sightings next time.
We've learned a lot throughout this project. Improving the ability to combine maps with time-series data effectively conveyed some key trends in bird sightings, and using interactive graphs also provides us with chances to offer the viewers more intriguing engagement opportunities, enabling them to explore specific species and seasons.
Lastly, as bird enthusiasts ourselves, we can't wait to benefit from our own analysis and interact with our favorite bird friends next time in Manhattan!