# Introduction
Both members of the group share a passion for birds and often spend hours in parks in New York, eagerly waiting for the delightful and long-awaited arrivals of various bird species. Inspired by our love for these avian creatures, we have decided to start a data science project dedicated to understanding birds, their unique traits, habitat preferences, and behavioral patterns. By exploring bird sightings and studying their characteristics across New York City, especially Manhattan, we wish to uncover patterns and insights that can enrich our bird-watching adventures. We hope that this project will not only enhance our ability to identify different bird species with confidence but also help us better understand their habits and factors impacting their “mysterious” appearances. In this way, our interactions with our feathered friends should be smoother and more informed.
More specifically, we want this project to help fellow bird enthusiasts maximizing their birdwatching experiences in Manhattan by offering suggestions and recommendations across three key areas - location, time, and species-specific guidance. We identify the best locations and optimal time periods for general birdwatching in NYC and provide targeted insights for those seeking specific species. We hope that our project can indeed enrich birdwatching experiences make it easier for enthusiasts to connect with their favorite species in NYC.